# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Jeremy Dolinsky Photography"
subtitle: ""
author: "Jeremy Dolinsky"
header:
 title: "Photography"
 subtitle: "by Jeremy Dolinsky"
footer:
 name: "Hi, my name is Jeremy"
 bio: "I am a photographer from Edmonton. I like to look at the world from a different point of view."
web_design: "JD"
social_urls:
  facebook: "https://www.facebook.com/Jeremy-Dolinsky-Photography-111741716151078"
  twitter: "https://twitter.com/jeremydolinsky"
  instagram: "https://www.instagram.com/jeremydolinskyphotography/"
  dribbble: ""
  linkedin: ""
  github: ""
